Processamento de Imagens
Mural
Atividades
Pessoas

Processamento de Imagens
Próximas atividades
Data de entrega: segunda-feira
23:59 – Projeto Parcial 2
Data de entrega: terça-feira
23:59 – UA 03 - Aulas 23 e 24 - Questionário - PI 2020
Visualizar tudo

Escreva um aviso para sua turma
Atividade: "UA 03 - Aulas 25 e 26 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 03 - Aulas 25 e 26 - Questionário - PI 2020
Criado em: 11:5711:57
Atividade: "UA 03 - Aulas 23 e 24 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 03 - Aulas 23 e 24 - Questionário - PI 2020
Criado em: 11:5611:56

Aviso: "UA 03 - Aulas 25 e 26"
Siovani Cintra Felipussi
Criado em: 08:2008:20 Editado às 11:51
UA 03 - Aulas 25 e 26

Aprox_Poligonal.rar
Arquivo compactado

rice_binary.png
Imagem

maior_menor_eixo.m
Objective-C

Cadeia.rar
Arquivo compactado

Assinaturas.rar
Arquivo compactado

regprop.m
Objective-C

regperim.m
Objective-C

separa_arroz.m
Objective-C

UA 03 - Aula 26 - PI 2020
Vídeo

UA 03 - Aula 25 - chat - PI 2020
Texto

UA 03 - Aula 25 - PI 2020
Vídeo

UA 3 - Aula 26 - PI 2020.pdf
PDF

UA 3 - Aula 25 - PI 2020.pdf
PDF

Atividade: "Projeto Parcial 2"
Siovani Cintra Felipussi postou uma nova atividade: Projeto Parcial 2
Criado em: 4 de dez.4 de dez.
12 comentários da turma

Aviso: "UA 03 - Aulas 23 e 24"
Siovani Cintra Felipussi
Criado em: 4 de dez.4 de dez. Editado às 4 de dez.
UA 03 - Aulas 23 e 24

UA 03 - Aula 23 - chat - PI 2020
Texto

aula_23_wat.m
Objective-C

UA 03 - Aula 23 - PI 2020
Vídeo

UA 03 - Aula 23 - PI 2020.pdf
PDF

UA 03 - Aula 24 - PI 2020
Vídeo

UA 03 - Aula 24 - PI 2020.pdf
PDF

aula_24.m
Objective-C

Atividade: "UA 03 - Aulas 21 e 22 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 03 - Aulas 21 e 22 - Questionário - PI 2020
Criado em: 26 de nov.26 de nov. Editado às 11:57

Aviso: "UA 03 - Aulas 21 e 22"
Siovani Cintra Felipussi
Criado em: 25 de nov.25 de nov. Editado às 26 de nov.
UA 03 - Aulas 21 e 22

UA 03 - Aula 21 - PI 2020.pdf
PDF

open.m
Objective-C

UA 03 - Aula 21 - chat - PI 2020
Texto

UA 03 - Aula 21 - PI 2020
Vídeo

UA 03 - Aula 21 - PI 2020.pdf
PDF

UA 03 - Aula 22 - PI 2020 - parte 1
Vídeo

UA 03 - Aula 22 - PI 2020.pdf
PDF

UA 03 - Aula 22 - PI 2020 - parte 2
Vídeo

cresc_regiao - octave.m
Objective-C

Atividade: "UA 02 - Aulas 19 e 20 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 02 - Aulas 19 e 20 - Questionário - PI 2020
Criado em: 20 de nov.20 de nov.

Aviso: "UA 02 - Aulas 19 e 20"
Siovani Cintra Felipussi
Criado em: 18 de nov.18 de nov. Editado às 20 de nov.
UA 02 - Aulas 19 e 20

UA 02 - Aula 20 - PI 2020.pdf
PDF

UA 02 - Aula 20 - PI 2020 - parte 2
Vídeo

UA 02 - Aula 20 - PI 2020 - parte 1
Vídeo

UA 02 - Aula 19 - PI 2020.pdf
PDF

UA 02 - Aula 19 - PI 2020
Vídeo

UA 02 - Aula 19 - chat - PI 2020
Texto

UA 02 - Aula 19 - Apoio.pdf
PDF

fft_2.m
Objective-C

dft.m
Objective-C

ex_fft_filter2_direc.m
Objective-C

ex_fft_filter2_low_pass.m
Objective-C

ex_fft2.m
Objective-C

fft.m
Objective-C

Atividade: "UA 02 - Aulas 17 e 18 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 02 - Aulas 17 e 18 - Questionário - PI 2020
Criado em: 16 de nov.16 de nov.
Atividade: "UA 02 - Aulas 15 e 16 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 02 - Aulas 15 e 16 - Questionário - PI 2020
Criado em: 12 de nov.12 de nov.

Aviso: "Aulas 17 e 18"
Siovani Cintra Felipussi
Criado em: 11 de nov.11 de nov. Editado às 13 de nov.
Aulas 17 e 18

UA 02 - Aula 17 e 18 - PI 2020
Vídeo

UA 02 - Aula 17 e 18 - chat - PI 2020
Texto

UA 02 - Aula 17 e 18 - PI 2020.pdf
PDF


Aviso: "UA 02 - Aulas 15 e 16"
Siovani Cintra Felipussi
Criado em: 21 de out.21 de out. Editado às 22 de out.
UA 02 - Aulas 15 e 16

direcoes.m
Objective-C

vizinhos.m
Objective-C

Highboost.m
Objective-C

UA 02 - Aula 15 - PI
Vídeo

UA 02 - Aula 16 - PI 2020 - parte 1
Vídeo

UA 02 - Aula 16 - PI 2020 - parte 2
Vídeo

UA 02 - Aula 16 - PI 2020.pdf
PDF

UA 02 - Aula 15 - PI 2020.pdf
PDF

UA 02 - Aula 15 - chat - PI 2020
Texto

Atividade: "Proposta de Projeto Final"
Siovani Cintra Felipussi postou uma nova atividade: Proposta de Projeto Final
Criado em: 14 de out.14 de out.
Atividade: "UA 02 - Aulas 13 e 14 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 02 - Aulas 13 e 14 - Questionário - PI 2020
Criado em: 14 de out.14 de out.

Aviso: "UA 02 - Aulas 13 e 14"
Siovani Cintra Felipussi
Criado em: 13 de out.13 de out. Editado às 14 de out.
UA 02 - Aulas 13 e 14

reconhecimento de padrões.mp4
Vídeo

sensoriamento remoto.mp4
Vídeo

análise de imagens.mp4
Vídeo

detecta.mp4
Vídeo

UA 2 - Aula 14 - PI 2020.pdf
PDF

UA 2 - Aula 13 - PI 2020.pdf
PDF

UA 02 - Aula 13 - chat - PI 2020
Texto

UA 02 - Aula 14 - PI 2020
Vídeo

UA 02 - Aula 13 - PI 2020
Vídeo


Aviso: "UA 02 - Aulas 11 e 12"
Siovani Cintra Felipussi
Criado em: 13 de out.13 de out.
UA 02 - Aulas 11 e 12

UA 2 - Aula 11 e 12 - PI 2020.pdf
PDF


Aviso: "Prezad@s, Na próxima quarta-feira 07/10…"
Siovani Cintra Felipussi
Criado em: 5 de out.5 de out.
Prezad@s,

Na próxima quarta-feira 07/10 as 8 h 00 será a devolutiva do Projeto Parcial 1 e recomendo que pelo menos 1 integrante do grupo esteja na aula síncrona (inclusive para os grupos que com nota 10,0). Haverá uma segunda sala virtual que conversarei com cada grupo sobre o PP1.
Em anexo as notas.

att

Prof. Siovani

Grupos PI.pdf
PDF

Atividade: "UA 02 - Aulas 09 e 10 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 02 - Aulas 09 e 10 - Questionário - PI 2020
Criado em: 30 de set.30 de set.

Aviso: "UA 02 - Aulas 09 e 10"
Siovani Cintra Felipussi
Criado em: 30 de set.30 de set. Editado às 30 de set.
UA 02 - Aulas 09 e 10

UA 02 - Aula 09 - PI 2020.pdf
PDF

UA 02 - Aula 10 - PI 2020.pdf
PDF

UA 02 - Aula 09 - chat - PI 2020
Texto

UA 02 - Aula 09 - PI 2020
Vídeo

UA 02 - Aula 10 - PI 2020
Vídeo

Atividade: "Projeto Parcial 1"
Siovani Cintra Felipussi postou uma nova atividade: Projeto Parcial 1
Criado em: 28 de set.28 de set. Editado às 28 de set.
10 comentários da turma
Atividade: "UA 02 - Aulas 07 e 08 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 02 - Aulas 07 e 08 - Questionário - PI 2020
Criado em: 24 de set.24 de set.

Aviso: "UA 02 - Aulas 07 e 08"
Siovani Cintra Felipussi
Criado em: 23 de set.23 de set. Editado às 24 de set.
UA 02 - Aulas 07 e 08

Banco de Imagens.rar
Arquivo compactado

equaliza.m
Objective-C

splitting.m
Objective-C

quantiza.m
Objective-C

UA 02 - Aula 08 - PI 2020.pdf
PDF

UA 02 - Aula 07 - PI 2020.pdf
PDF

UA 02 - Aula 08 - PI 2020
Vídeo

UA 02 - Aula 06 - chat - PI 2020
Texto

UA 02 - Aula 07 - PI 2020
Vídeo

hist_label.m
Objective-C

binariza.m
Objective-C

alt_global.m
Objective-C

label_count.m
Objective-C

Pergunta: "Preenchimento de planilha com os integrantes dos Grupos"
Siovani Cintra Felipussi postou uma nova pergunta: Preenchimento de planilha com os integrantes dos Grupos
Criado em: 21 de set.21 de set.
Atividade: "UA 01 e 02 - Aulas 05 e 06 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 01 e 02 - Aulas 05 e 06 - Questionário - PI 2020
Criado em: 16 de set.16 de set.

Aviso: "UA 01 e 02 - Aulas 05 e 06"
Siovani Cintra Felipussi
Criado em: 16 de set.16 de set. Editado às 18 de set.
UA 01 e 02 - Aulas 05 e 06

Eucl_city_chess_octave.m
Objective-C

UA 1 - Aula 05 - PI 2020.pdf
PDF

UA 01 - Aula 05 - chat - PI 2020
Texto

UA 01 - Aula 05 - PI 2020
Vídeo

UA 02 - Aula 06 - PI 2020.pdf
PDF

UA 02 - Aula 06 - PI 2020
Vídeo

rice_binary.png
Imagem

label_count.m
Objective-C

blobs.tif
Imagem

Sem título.png
Imagem

Siovani Cintra Felipussi20 de set.
Olá Pessoal, 
Nos finais de semana eu fico on em alguns momentos por isso a demora em responder. Lendo as msgs de vcs é possível verificar que em princípio há alguma restrição de vossas contas, navegadores, antivírus, enfim, parece-me que são restrições locais e para comprovar acessei novamente as configurações do Google Sala de Aula estão todas liberadas para download (uma das formas de baixar é clicando no botão imprimir). As imagens eu consegui baixar também com minha conta de aluno (ao abrir a imagem escolhi a opção abrir uma nova janela e foi possível baixar). Espero ter ajudado. Abs a todos e estou a disposição.

Siovani

Atividade: "UA 01 - Aulas 03 e 04 - Questionário - PI 2020"
Siovani Cintra Felipussi postou uma nova atividade: UA 01 - Aulas 03 e 04 - Questionário - PI 2020
Criado em: 14 de set.14 de set. Editado às 14 de set.

Aviso: "UA01 - Aulas 03 e 04 - Em 14/09…"
Siovani Cintra Felipussi
Criado em: 11 de set.11 de set.
UA01 - Aulas 03 e 04 - Em 14/09 disponibilizarei o questionário

UA 01 - Aula 03 - PI 2020.pdf
PDF

UA 1 - Aula 04 - Vídeo 1 - PI 2020.wmv
Windows Media Player

UA 01 - Aula 04 - PI 2020.pdf
PDF

paleta.m
Objective-C

PI - UA 01 - Aula 03 - Chat
Texto

UA 01 - Aula 03 - PI 2020
Vídeo

UA 01 - Aula 04 - PI 2020 - parte 1
Vídeo

UA 01 - Aula 04 - PI 2020 - parte 2
Vídeo


Aviso: "Prezad@s, Revoguei o link anterior do…"
Siovani Cintra Felipussi
Criado em: 8 de set.8 de set.
Prezad@s,

Revoguei o link anterior do Google Meet, utilizaremos meet.google.com/yii-pevk-jvr até o final da disciplina.

Att

Prof. Siovani


Aviso: "Prezad@s, Recomendo que utilizem o…"
Siovani Cintra Felipussi
Criado em: 4 de set.4 de set.
Prezad@s,

Recomendo que utilizem o @estudante para uso do GSuite da UFSCar e saliento que será necessário esse domínio para responder aos questionários.
Enviem para siovani@ufscar.br até as 13h00 de 07/09 teu email @estudante para cadastro no Google Sala de Aula.

Att

Siovani


clear all 
close all
clc
I = imread('snowflakes.png');
figure, imshow(I), title('imagem original');
%claheI = adapthisteq(I,'NumTiles',[10 10]);
temp_I = histeq(I);
temp_I = imadjust(temp_I);
temp_I=uint8((temp_I)*255);
figure, imshow(temp_I), title('Imagem com histograma equalizado');
radius_range = 1:22;
intensity_area = zeros(size(radius_range));
for counter = radius_range
    remain = imopen(temp_I, strel('disk', counter,0));
    intensity_area(counter + 1) = sum(remain(:));  
end
figure, plot(intensity_area, 'm - *')
grid on
title('Sum of pixel values in opened image versus radius')
xlabel('radius of opening (pixels)')
ylabel('pixel value sum of opened objects (intensity)')
intensity_area_prime = diff(intensity_area);
figure, plot(intensity_area_prime, 'm - *')
grid on
title('Granulometry (Size Distribution) of Snowflakes')
%ax = gca;
XTick = [0 2 4 6 8 10 12 14 16 18 20 22];
xlabel('radius of snowflakes (pixels)')
ylabel('Sum of pixel values in snowflakes as a function of radius')
open5 = imopen(temp_I,strel('disk',5,0));
open6 = imopen(temp_I,strel('disk',6,0));
rad5 = imsubtract(open5,open6);
figure, imshow(rad5,[]), title('snowflakes com raio 5');
open.m
Exibindo open.m.